### PR TITLE
63 Refined UI (a lot)

### LINKED ISSUE #63: Refine UI for the Add Staff & Reports pages.
## Refine UI for the Add Staff & Reports page
- [ ] /add-staff currently overflows out of view 
- [ ] /add-staff could also use some minor style refining.
- [ ] /report-gen has similar issues and a lack of styles.
- [x] Also create separate route groups for both.

### PR DESCRIPTION
**Pull request by adelicia-js**
## Refined UI 
Closes #63 #70 #36 (kinda)
- Made NavTwo fixed, this should solve the issues with scrolling in various pages.
- Some modifications to NavOne styles.
- Made new route groups for /modify & /reports (hence, new URLs as well).
- Fixed role-based views in NavTwo for /settings. 
- Made skeletal /reports to WAYY prettier /reports.

Would like to add further refining, but will do that on a different branch.. :) 

Dashboard (try spotting the changes 🗿):
image

Report:
No Data:
image
With Data:
image

Settings:
image

### CODE REVIEW

**Comment by adelicia-js** [comment]
So much I still wanna do ;-;

**Comment by programmingMohit** [comment]
image
Report with data

**Review by programmingMohit — APPROVED** [review]
The UI changes are gorgeous! 💚 Looks perfect and good to go. 
(ady stawp workin you making us look bad ;-; )

**Review by Shanki200801 — APPROVED** [review]
Looks good

**Pull request merged**
