### PR TITLE
58 Add achievement modals to all categories pages

### LINKED ISSUE #58: Fix existing components in the `Add [Category_Item]` section of the Category pages.
- [x] Create new modal components to replace previously existing popovers.
- [x] Fix the input tag value errors
- [x] Add file upload functions for images: Conferences, Journals & Patents.
- [x] Under /my-workshops, the label for 'Workshop organized by' should only be displayed if the user checks 'Attended' in the previous question.
- [x] Faculty ID input should be read-only.
- [x] Faculty ID input should already be auto-filled. 
- [x] Under /my-conferences, the label for 'Proceedings front page' should only be displayed if the checkbox for the previous question is checked. 
- [x] Change all buttons to 'Add [category_item]', instead of 'Update'

### PR DESCRIPTION
**Pull request by adelicia-js**
## Added new add achievement modals to all categories pages
- Got rid of popovers previously used
- Added modals similar to the ones used for editing/updating details in the category tables.
- Fixed some inconsistencies in the forms.
- Added file upload db functions (thanks @Shanki200801!) - have to check this functionality.
- Other minor issues listed in #58.

Closes #58.

### CODE REVIEW

**Review by programmingMohit — CHANGES_REQUESTED** [review]
Field to upload conference certificate image missed out, need to add that.
Also the buttons should be called something other than update perhaps?

Rest looks good to go!

**Comment by Shanki200801** [comment]
Under add conferences,proceedings fp should only be displayed if checkbox is ticked. It should be hidden by default.

**Comment by adelicia-js** [comment]
> Field to upload conference certificate image missed out, need to add that. Also the buttons should be called something other than update perhaps?
> 
> Rest looks good to go!

> Under add conferences,proceedings fp should only be displayed if checkbox is ticked. It should be hidden by default.

Kay, will add these

**Comment by adelicia-js** [comment]
> Field to upload conference certificate image missed out, need to add that. Also the buttons should be called something other than update perhaps?
> 
> Rest looks good to go!

> Under add conferences,proceedings fp should only be displayed if checkbox is ticked. It should be hidden by default.

Added all requested changes! Please review again.

**Review by programmingMohit — APPROVED** [review]

**Review by Shanki200801 — APPROVED** [review]

**Comment by adelicia-js** [comment]
image
(For reference)

**Pull request merged**
