### PR TITLE
17 category pages

### PR DESCRIPTION
**Pull request by programmingMohit**
- UI of the category pages done as given by the Figma design
- Table pulls and displays current user data for corresponding categories
- Add new button currently employs existing popover component to add data; needs to be changed; create a separate issue for it

### CODE REVIEW

**Review by adelicia-js — APPROVED** [review]
Looks good to go! Love it.

**Review by adelicia-js — CHANGES_REQUESTED** [review]
Looks good! Add the routes to profile and logout in the category pages layout and this will be merged!

**Comment by Shanki200801** [comment]
1. The table should say something like "No entries in this category" if no item exists
2. Add an edit button next to each row so that the staff can modify their entries

Other than those 2 I think it's all good!

**Review by Shanki200801 — CHANGES_REQUESTED** [review]
The table should say something like "No entries in this category" if no item exists
    Add an edit button next to each row so that the staff can modify their entries

Other than those 2 I think it's all good!

**Comment by programmingMohit** [comment]
> Looks good! Add the routes to profile and logout in the category pages layout and this will be merged!

Pushed changes. Re-requested a review

**Comment by Shanki200801** [comment]
> 1. The table should say something like "No entries in this category" if no item exists
> 

This will be made into a separate issue next sprint

**Review by Shanki200801 — APPROVED** [review]

**Review by adelicia-js — APPROVED** [review]

**Pull request merged**
