### PR TITLE
fixed smol issue in /my-workshops; updated .gitignore to protect our app 🥴

### PR DESCRIPTION
**Pull request by adelicia-js**
- When a user adds a workshop that they've organized, `organisedBy` now displays "Self".
- Updated `.gitignore` to hide local env file. 🗿

### CODE REVIEW

**Review by programmingMohit — APPROVED** [review]
Looks good to go!
DO NOT PUSH TO MERGED BRANCH GURL

**Comment by adelicia-js** [comment]
nvm did not fully fix ;-;

**Review by programmingMohit — APPROVED** [review]

**Review by adelicia-js — COMMENTED** [review]
Oooo nice!

**Comment by adelicia-js** [comment]
> Looks good to go! DO NOT PUSH TO MERGED BRANCH GURL

😼

**Review by Shanki200801 — APPROVED** [review]
Lg

**Pull request merged**
