### PR TITLE
28 create page for report generation

### PR DESCRIPTION
**Pull request by Shanki200801**
1. Report generation for full data as well as light data (can be renamed later)
2. Full report downloads 4 csv files 1 for each category
3. Light report downloads the data being displayed on table
4. Filters option to select staff name gets all staff present in the same dept as the editor / HOD
5. Filter option to search for specific name in title reduces data shown as more letters are typed
6. Have installed 2 packages so y'all need to npm i.
7. Design is temporary, have reused Mohit's table styles
8. The alignment of filters and the report table has to be adjusted.
9. The refinements can be made into a new issue

### CODE REVIEW

**Comment by adelicia-js** [comment]
Oops, code a bit broken still, merge with main and try again!

**Review by programmingMohit — CHANGES_REQUESTED** [review]
Selecting a certain type of submission, say, conference and then clicking on download full report throws this error
image

Needs to be fixed I suppose

Also in Profile.tsx, Account should come from dashboard not profile folder; causes error
`import Account from "@/components/profile/Account";`
(Importing it still leaves the page wonky, overlapping stuff I suppose)

**Comment by Shanki200801** [comment]
@programmingMohit Fixed the 2 errors.

**Comment by adelicia-js** [comment]
WhatsApp Image 2023-10-23 at 08 49 37_831ebc12

This error will show up, and disappear when you navigate to localhost:3000/test

Do not incorporate the erroneous code in the actual backend.

Good to go, otherwise.

**Review by adelicia-js — APPROVED** [review]

**Review by programmingMohit — APPROVED** [review]

**Pull request merged**
