### PR TITLE
38 - Integrated Profile & Dashboard, Profile is now Settings, Minor style overhaul.

### LINKED ISSUE #38: Integrate components of Profile & Dashboard.
## Integrate components of Profile & Dashboard.
- Dashboard no longer has a carousel
- `Account` component on Dashboard to be replaced with `Account` component from Profile.
- Profile page is now just Settings page => It will consist of a single `Settings` component.

## Tasks for follow-up issue
- Add a chart component using Chart.js & react-chartjs post-integration. 

### Relevant references:
- https://www.chartjs.org/
- https://www.npmjs.com/package/react-chartjs-2

### PR DESCRIPTION
**Pull request by adelicia-js**
### Integrated Profile & Dashboard, Profile is now Settings
- Renamed route group `(profile)` to `(settings)`. 
   - New URL for Settings page: localhost:3000/settings
- Integrated components from `Profile` into `Dashboard`

### Style Refining
- Styling overhaul for app, mostly font changes.
- `Categories` also saw some layout changes.
- `NavOne` components for all route groups optimized.
- `Login` refined slightly.

Succesfully closes #38.

### CODE REVIEW

**Review by SiddharthSai4701 — APPROVED** [review]

**Review by Shanki200801 — APPROVED** [review]
Pls send ss next time

**Comment by adelicia-js** [comment]
> Pls send ss next time

Okie, here are a few for future reference:
image
Dashboard (WIP)
image
image
Settings
image
Categories
image
Login

**Comment by Shanki200801** [comment]
Looks good!

**Comment by adelicia-js** [comment]
> Looks good!

Thenks, I am totally sane after playing with `NavOne`! 😼

**Pull request merged**
