### PR TITLE
Implemented Profile page.

### PR DESCRIPTION
**Pull request by adelicia-js**
- Added 3 components: Account, Socials & Settings.
- I need help with deciding what titles to be added under settings. @Shanki200801 
- Responsiveness is pending, it's kinda wonky still.
- Also edited/refined dashboard a bit.

This will remain a draft till points 2 & 3 are addressed.

### CODE REVIEW

**Review by programmingMohit — APPROVED** [review]
Looks good to go!

**Comment by Shanki200801** [comment]
weird things happening in profile page. Ik mobile responsiveness. The [welcome back text] isn't scrolling out of screen properly. idk if that's intentional
image

image

**Comment by adelicia-js** [comment]
> weird things happening in profile page . The [welcome back text] isn't scrolling out of screen properly. idk if that's intentional image
> 
> image

Test on your laptop and send ss. It's not optimized for mobile. 🙃

**Comment by adelicia-js** [comment]
@Shanki200801 please test the settings component. To do so, pull these changes & navigate to localhost:3000/profile/test 

Let me know how to proceed/add backend functionality yourself and push changes, thank you!

**Comment by adelicia-js** [comment]
> weird things happening in profile page . The [welcome back text] isn't scrolling out of screen properly. idk if that's intentional image
> 
> image

Will address this in #36 after our app is fully functional :)

**Comment by adelicia-js** [comment]
## Final UI:
image

- Integrated test Settings component into actual profile page for `Socials` & `Settings`.

For a new issue:
- Need to figure out how to update profile picture.
- Backend functions to be added.
- Mild responsiveness changes (will be addressed by #36)

**Review by programmingMohit — APPROVED** [review]
The UI looks good to go, this issue can be closed. The backend can be tackled in another issue. The design and layout are beautiful!

**Comment by adelicia-js** [comment]
> The UI looks good to go, this issue can be closed. The backend can be tackled in another issue. The design and layout are beautiful!

Thank u! 🥰

**Pull request merged**
